// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkS_AZhDcda1JYL5mNDr0qYis4iE-dsQI',
    appId: '1:311157187495:web:532f5e85fd3a62dc544c82',
    messagingSenderId: '311157187495',
    projectId: 'finance-app-fcdfb',
    authDomain: 'finance-app-fcdfb.firebaseapp.com',
    storageBucket: 'finance-app-fcdfb.firebasestorage.app',
    measurementId: 'G-PDHFK5JHHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1rjivyTFxUfxjQ3JwdLCceyn0Mh7TV1w',
    appId: '1:311157187495:android:c2e351b13408e56f544c82',
    messagingSenderId: '311157187495',
    projectId: 'finance-app-fcdfb',
    storageBucket: 'finance-app-fcdfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgNNC5B1asaz1DWqE3yvuscgvZFM0v3_Q',
    appId: '1:311157187495:ios:8a3a158870eddf24544c82',
    messagingSenderId: '311157187495',
    projectId: 'finance-app-fcdfb',
    storageBucket: 'finance-app-fcdfb.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgNNC5B1asaz1DWqE3yvuscgvZFM0v3_Q',
    appId: '1:311157187495:ios:8a3a158870eddf24544c82',
    messagingSenderId: '311157187495',
    projectId: 'finance-app-fcdfb',
    storageBucket: 'finance-app-fcdfb.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkS_AZhDcda1JYL5mNDr0qYis4iE-dsQI',
    appId: '1:311157187495:web:28ec5802f63d1471544c82',
    messagingSenderId: '311157187495',
    projectId: 'finance-app-fcdfb',
    authDomain: 'finance-app-fcdfb.firebaseapp.com',
    storageBucket: 'finance-app-fcdfb.firebasestorage.app',
    measurementId: 'G-M3F46V6GHB',
  );
}
